name: ZQPortal
main: cn.yzq25.portal.PortalMain
version: "1.0.0"
api: ["1.0.0"]
load: POSTWORLD

author: Yanziqing25
description: 传送门插件
website: http://www.yzq25.cn

permissions:
  portal.command:
    children:
      portal.command.setportal:
        default: op
      portal.command.removeportal:
        default: op
      portal.command.removespace:
        default: op
      portal.command.cancelportal:
        default: op
