name: ZQPortal
main: cn.yzking.portal.PortalMain
version: "2.0.2"
api: ["1.0.13"]
load: POSTWORLD
softdepend:
- ZQExtension
- ZQWorlds
depend:
- ZQExtension

author: Yanziqing25
description: 传送门插件
website: https://www.yzking.cn

permissions:
  portal.command.setportal:
    default: op
  portal.command.deleteportal:
    default: op
  portal.command.cancelportal:
    default: op